"""
Output formatting for final picks.
Formats picks for display and delivery.
"""
from datetime import datetime
from typing import List
import structlog

from data.models.schemas import PropAnalysis, FormattedPick
from generation.llm_analyzer import generate_risk_notes

logger = structlog.get_logger()


def format_pick(analysis: PropAnalysis, rank: int = 1) -> FormattedPick:
    """Format a single prop analysis into final output format.

    Args:
        analysis: The prop analysis
        rank: Ranking position (1 = best)

    Returns:
        FormattedPick object
    """
    prop = analysis.prop
    direction = analysis.direction.upper()

    # Format projected range
    projected_range = f"{analysis.projected_low:.1f} - {analysis.projected_high:.1f}"

    # Get best odds for this direction
    odds = prop.over_odds if analysis.direction == "over" else prop.under_odds

    # Generate risk notes if not already present
    risk_notes = analysis.risk_notes or generate_risk_notes(analysis)
    risk_text = "; ".join(risk_notes) if risk_notes else "Standard risks apply"

    return FormattedPick(
        player_name=analysis.player.name,
        prop_type=_format_prop_type(prop.prop_type),
        direction=direction,
        line=prop.line,
        book=prop.book,
        odds=odds,
        projected_range=projected_range,
        analysis=analysis.narrative,
        risk_notes=risk_text,
        confidence_rank=rank
    )


def _format_prop_type(prop_type: str) -> str:
    """Format prop type for display.

    Args:
        prop_type: Internal prop type string

    Returns:
        Human-readable prop type
    """
    mappings = {
        "points": "Points",
        "rebounds": "Rebounds",
        "assists": "Assists",
        "threes": "3-Pointers Made",
        "fg3m": "3-Pointers Made",
        "pts_rebs_asts": "Points + Rebounds + Assists",
        "pra": "Points + Rebounds + Assists",
        "pts_asts": "Points + Assists",
        "pts_rebs": "Points + Rebounds",
        "rebs_asts": "Rebounds + Assists",
        "double_double": "Double-Double"
    }
    return mappings.get(prop_type, prop_type.replace("_", " ").title())


def format_picks_text(picks: List[FormattedPick]) -> str:
    """Format all picks as plain text.

    Args:
        picks: List of formatted picks

    Returns:
        Plain text output
    """
    lines = []
    lines.append("=" * 60)
    lines.append(f"NBA PLAYER PROPS - {datetime.now().strftime('%B %d, %Y')}")
    lines.append("=" * 60)
    lines.append("")

    for i, pick in enumerate(picks, 1):
        lines.append(f"PICK #{i}")
        lines.append("-" * 40)
        lines.append(f"{pick.player_name} - {pick.prop_type} - {pick.direction} {pick.line}")
        lines.append(f"Book: {pick.book}")
        lines.append(f"Odds: {_format_odds(pick.odds)}")
        lines.append(f"Projected Range: {pick.projected_range}")
        lines.append("")
        lines.append(pick.analysis)
        lines.append("")
        lines.append(f"Risk Notes: {pick.risk_notes}")
        lines.append("")
        lines.append("=" * 60)
        lines.append("")

    lines.append("Generated by NBA Prop Analyzer")
    lines.append(f"Analysis completed at {datetime.now().strftime('%I:%M %p ET')}")

    return "\n".join(lines)


def format_picks_html(picks: List[FormattedPick]) -> str:
    """Format all picks as HTML for email.

    Args:
        picks: List of formatted picks

    Returns:
        HTML output
    """
    html_parts = []

    html_parts.append("""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
            h1 { color: #1a1a2e; border-bottom: 3px solid #4a4e69; padding-bottom: 10px; }
            .pick { background: #f8f9fa; border-radius: 8px; padding: 20px; margin: 20px 0; }
            .pick-header { font-size: 18px; font-weight: bold; color: #22223b; margin-bottom: 10px; }
            .pick-details { color: #4a4e69; margin: 5px 0; }
            .analysis { margin: 15px 0; line-height: 1.6; }
            .risk { background: #fff3cd; padding: 10px; border-radius: 4px; font-size: 14px; }
            .odds-positive { color: #28a745; font-weight: bold; }
            .odds-negative { color: #dc3545; font-weight: bold; }
            .footer { text-align: center; color: #6c757d; margin-top: 30px; font-size: 12px; }
        </style>
    </head>
    <body>
    """)

    html_parts.append(f"""
        <h1>NBA Player Props - {datetime.now().strftime('%B %d, %Y')}</h1>
    """)

    for i, pick in enumerate(picks, 1):
        odds_class = "odds-positive" if pick.odds > 0 else "odds-negative"
        odds_str = _format_odds(pick.odds)

        html_parts.append(f"""
        <div class="pick">
            <div class="pick-header">
                PICK #{i}: {pick.player_name} - {pick.prop_type} - {pick.direction} {pick.line}
            </div>
            <div class="pick-details">
                <strong>Book:</strong> {pick.book} |
                <strong>Odds:</strong> <span class="{odds_class}">{odds_str}</span> |
                <strong>Projected:</strong> {pick.projected_range}
            </div>
            <div class="analysis">
                {pick.analysis}
            </div>
            <div class="risk">
                <strong>Risk Notes:</strong> {pick.risk_notes}
            </div>
        </div>
        """)

    html_parts.append(f"""
        <div class="footer">
            Generated by NBA Prop Analyzer<br>
            Analysis completed at {datetime.now().strftime('%I:%M %p ET')}
        </div>
    </body>
    </html>
    """)

    return "\n".join(html_parts)


def _format_odds(odds: int) -> str:
    """Format American odds for display.

    Args:
        odds: American odds integer

    Returns:
        Formatted string (e.g., "+120" or "-110")
    """
    if odds > 0:
        return f"+{odds}"
    return str(odds)


def format_picks_json(picks: List[FormattedPick]) -> dict:
    """Format picks as JSON-serializable dict.

    Args:
        picks: List of formatted picks

    Returns:
        Dict structure for JSON export
    """
    return {
        "date": datetime.now().isoformat(),
        "picks": [
            {
                "rank": pick.confidence_rank,
                "player": pick.player_name,
                "prop_type": pick.prop_type,
                "direction": pick.direction,
                "line": pick.line,
                "book": pick.book,
                "odds": pick.odds,
                "projected_range": pick.projected_range,
                "analysis": pick.analysis,
                "risk_notes": pick.risk_notes
            }
            for pick in picks
        ]
    }


def format_slack_blocks(picks: List[FormattedPick]) -> list:
    """Format picks as Slack blocks for webhook.

    Args:
        picks: List of formatted picks

    Returns:
        Slack blocks list
    """
    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"NBA Player Props - {datetime.now().strftime('%B %d, %Y')}"
            }
        },
        {"type": "divider"}
    ]

    for i, pick in enumerate(picks, 1):
        odds_str = _format_odds(pick.odds)

        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": (
                    f"*PICK #{i}*\n"
                    f"*{pick.player_name}* - {pick.prop_type} - {pick.direction} {pick.line}\n"
                    f"Book: {pick.book} | Odds: {odds_str} | Projected: {pick.projected_range}"
                )
            }
        })

        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": pick.analysis
            }
        })

        blocks.append({
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": f"_Risk Notes: {pick.risk_notes}_"
                }
            ]
        })

        blocks.append({"type": "divider"})

    return blocks
